### ISSUE TITLE
Error console

### ISSUE THREAD

**Issue by Spinogl** [aikidored/RemoteCommands#1]
[22:06:46] [Server thread/INFO]: Spinogl issued server command: /rb sendall test
[22:06:46] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rb' in plugin RemoteCommands v4.2
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.8.8.jar:git-PaperSpigot-445]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.8.8.jar:git-PaperSpigot-445]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched_1.8.8.jar:git-PaperSpigot-445]
    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched_1.8.8.jar:git-PaperSpigot-445]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched_1.8.8.jar:git-PaperSpigot-445]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.8.8.jar:git-PaperSpigot-445]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched_1.8.8.jar:git-PaperSpigot-445]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.8.8.jar:git-PaperSpigot-445]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_333]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_333]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched_1.8.8.jar:git-PaperSpigot-445]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched_1.8.8.jar:git-PaperSpigot-445]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
    at java.lang.Thread.run(Thread.java:750) [?:1.8.0_333]
Caused by: java.lang.NullPointerException
    at net.PluginDev.aiki.RC.main.getIndex(main.java:315) ~[?:?]
    at net.PluginDev.aiki.RC.main.sendBroadcast(main.java:479) ~[?:?]
    at net.PluginDev.aiki.RC.main.BSendAll(main.java:496) ~[?:?]
    at net.PluginDev.aiki.RC.main.onCommand(main.java:235) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.8.8.jar:git-PaperSpigot-445]
    ... 15 more

**Comment by Spinogl** [comment]
[21:58:17] [Server thread/WARN]: java.net.UnknownHostException: https://www.spigotmc.org/resources/remote-commands.74321/: Name or service not known
[21:58:17] [Server thread/WARN]:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
[21:58:17] [Server thread/WARN]:     at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
[21:58:17] [Server thread/WARN]:     at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
[21:58:17] [Server thread/WARN]:     at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
[21:58:17] [Server thread/WARN]:     at java.net.InetAddress.getAllByName(InetAddress.java:1193)
[21:58:17] [Server thread/WARN]:     at java.net.InetAddress.getAllByName(InetAddress.java:1127)
[21:58:17] [Server thread/WARN]:     at java.net.InetAddress.getByName(InetAddress.java:1077)
[21:58:17] [Server thread/WARN]:     at net.PluginDev.aiki.RC.main.UpdateChecker(main.java:560)
[21:58:17] [Server thread/WARN]:     at net.PluginDev.aiki.RC.main.loadPlugin(main.java:113)
[21:58:17] [Server thread/WARN]:     at net.PluginDev.aiki.RC.main.onEnable(main.java:101)
[21:58:17] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[21:58:17] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[21:58:17] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[21:58:17] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[21:58:17] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[21:58:17] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[21:58:17] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[21:58:17] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[21:58:17] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[21:58:17] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[21:58:17] [Server thread/WARN]:     at java.lang.Thread.run(Thread.java:750)
[21:58:17] [Thread-14/WARN]: Exception in thread "Thread-14" 
[21:58:17] [Thread-14/WARN]: java.lang.NullPointerException
[21:58:17] [Thread-14/WARN]:     at java.net.Socket.<init>(Socket.java:445)
[21:58:17] [Thread-14/WARN]:     at java.net.Socket.<init>(Socket.java:261)
[21:58:17] [Thread-14/WARN]:     at net.PluginDev.aiki.RC.main.UpdateCheckClient(main.java:579)
[21:58:17] [Thread-14/WARN]:     at net.PluginDev.aiki.RC.main.lambda$startUpdateClient$3(main.java:570)
[21:58:17] [Thread-14/WARN]:     at java.lang.Thread.run(Thread.java:750)

**Comment by Spinogl** [comment]
[04:30:13] [Server thread/INFO]: [RemoteCommands] Enabling RemoteCommands v4.2
[04:30:13] [Server thread/INFO]: ########################
[04:30:13] [Server thread/INFO]: # Remote Commands v4.1 #
[04:30:13] [Server thread/INFO]: ########################
[04:30:13] [Server thread/INFO]: [Remote Commands] Made by Aikidored
[04:30:13] [Server thread/INFO]: [Remote Commands] If you Enjoy. Please Leave a Review on the Spigot Page
[04:30:13] [Server thread/INFO]: [Remote Commands] Spigot: https://www.spigotmc.org/resources/remote-commands.74321/
[04:30:13] [Server thread/INFO]: [Remote Commands] Any Bugs or Issues? Contact me on Discord or Github
[04:30:13] [Server thread/INFO]: [Remote Commands] Discord: https://discord.gg/RYTfade
[04:30:13] [Server thread/INFO]: [Remote Commands] Github / Wiki: https://github.com/aikidored/RemoteCommands
[04:30:13] [Server thread/INFO]: [Remote Commands] Loading Plugin . . . 
[04:30:13] [Server thread/INFO]: [Remote Commands][Status] Config has been Loaded
[04:30:13] [Server thread/INFO]: [Remote Commands] Servers List has been Loaded
[04:30:13] [Server thread/INFO]: [Remote Commands] Messages.yml Loaded
[04:30:13] [Server thread/WARN]: java.net.UnknownHostException: https://www.spigotmc.org/resources/remote-commands.74321/: Name or service not known
[04:30:13] [Server thread/WARN]:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
[04:30:13] [Server thread/WARN]:     at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
[04:30:13] [Server thread/WARN]:     at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
[04:30:13] [Server thread/WARN]:     at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
[04:30:13] [Server thread/WARN]:     at java.net.InetAddress.getAllByName(InetAddress.java:1193)
[04:30:13] [Server thread/WARN]:     at java.net.InetAddress.getAllByName(InetAddress.java:1127)
[04:30:13] [Server thread/WARN]:     at java.net.InetAddress.getByName(InetAddress.java:1077)
[04:30:13] [Server thread/WARN]:     at net.PluginDev.aiki.RC.main.UpdateChecker(main.java:560)
[04:30:13] [Server thread/WARN]:     at net.PluginDev.aiki.RC.main.loadPlugin(main.java:113)
[04:30:13] [Server thread/WARN]:     at net.PluginDev.aiki.RC.main.onEnable(main.java:101)
[04:30:13] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[04:30:13] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[04:30:13] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[04:30:13] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[04:30:13] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[04:30:13] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[04:30:13] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[04:30:13] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[04:30:13] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[04:30:13] [Server thread/WARN]:     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[04:30:13] [Server thread/WARN]:     at java.lang.Thread.run(Thread.java:750)
